### ISSUE TITLE
Imports not found in Typescript 5.8.2

### ISSUE THREAD

**Issue by guillempuche** [supertokens/supertokens-auth-react#879]
After updating my repo from Typescript 5.7.2 to 5.8.2 https://devblogs.microsoft.com/typescript/announcing-typescript-5-8/, IDE complains regarding this package `Cannot find module 'supertokens-auth-react/recipe/session' or its corresponding type declarations.ts(2307)`

![Image](https://github.com/user-attachments/assets/0991d038-6dd3-4ef9-aa97-e450b2a3bcec)
